### PR TITLE
Remove feature flag for stabilising try_from

### PR DESCRIPTION
**Pull request by Bathtor**
Please do a new deploy for this.

Should work on nightly and beta, and soon on stable channel as well.

There are also a few "unused" warnings that should either be tested for or remove, I suppose? I didn't touch them, though.

### CODE REVIEW

**Comment by Bathtor** [comment]
Oh, and maybe add this to Travis, so you know if PRs break anything.

**Comment by Bathtor** [comment]
Ping?

**Comment by johanmickos** [comment]
@Bathtor Apologies for the delay, certain notifications apparently don't reach my email account.

PR looks fine, though I don't have the bandwidth this week to address the `unused` warnings & CI. I'll ping ya when I do.

**Review by johanmickos — APPROVED** [review]

**Comment by johanmickos** [comment]
@Bathtor Published v0.2.0 to https://crates.io/crates/bitfields

**Pull request merged**
